### ISSUE TITLE
Better error messages when the XML-RPC fails

### ISSUE THREAD

**Issue by samiit** [odow/NEOS.jl#5] opened 2016-06-22 04:33 UTC
When I try to create the solver object:
`s = NEOSSYMPHONYSolver(time_limit=60)`
I get the error.
`ERROR: XML-RPC failed`

Any fix?

**Comment by odow** [comment] 2016-06-22 05:03
Have you checked out the `updatesformpb0.4` branch? I'm just about to merge https://github.com/odow/NEOS.jl/pull/4. 

Can you try

```
s = NEOSServer()

println(welcome(s))

println(version(s))

println(getSolverTemplate(s, :MILP, :SYMPHONY, :MPS))
```

**Comment by odow** [comment] 2016-06-22 05:05
Just merged. Could you please run `Pkg.checkout("NEOS")` and retry.

**Comment by samiit** [comment] 2016-06-22 05:32
Problem persists.

**Comment by odow** [comment] 2016-06-22 05:42
Are you on a network that doesn't allow XML-RPC requests?

```
using NEOS
s = NEOSServer()
name = "version"
xml = NEOS.XMLDocument()
mthd =  NEOS.create_root(xml, "methodCall")
mname = NEOS.new_child(mthd, "methodName")

NEOS.add_text(mname, name)
xml = string(xml)

hdrs = Dict{AbstractString, AbstractString}("user-agent" => s.useragent, "host" => s.host, "content-type" => s.contenttype, "content-length" => string(length(xml)))

res = NEOS.post(s.host; headers=hdrs, data=xml)
@show res.status
println(bytestring(res.data))
```

**Comment by samiit** [comment] 2016-06-22 05:55
Well, the output is:

```
res.status = 404
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL / was not found on this server.</p>
</body></html>
```

**Comment by odow** [comment] 2016-06-22 06:01
Seems like a firewall issue.

Can you please run

```
versioninfo()
Pkg.installed()
```

**Comment by samiit** [comment] 2016-06-22 06:11
`versioninfo()`

```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas ()
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

`Pkg.installed()`

```
Dict{ASCIIString,VersionNumber} with 55 entries:
  "Libz"           => v"0.1.1"
  "ForwardDiff"    => v"0.1.8"
  "Memoize"        => v"0.0.1"
  "ExcelReaders"   => v"0.5.0"
  "Lazy"           => v"0.10.1"
  "ZMQ"            => v"0.3.2"
  "ArrayViews"     => v"0.6.4"
  "DataStructures" => v"0.4.4"
  "Compat"         => v"0.8.1"
  "Calculus"       => v"0.1.15"
  "GZip"           => v"0.2.19"
  "MathProgBase"   => v"0.4.3"
  "StatsFuns"      => v"0.2.2"
  "HttpParser"     => v"0.1.1"
  "Requests"       => v"0.3.7"
  "DataFrames"     => v"0.7.3"
  "NEOS"           => v"0.0.1+"
  "Clp"            => v"0.2.0"
  "FactCheck"      => v"0.4.3"
  ⋮                => ⋮
```

**Comment by odow** [comment] 2016-06-22 22:17
@samiit my guess is that your network is blocking XML-RPC requests. Could this be the case? 

Unfortunately there isn't really any fix on my end.

**Comment by samiit** [comment] 2016-06-23 04:37
Sure I'll check that out and if this is the case, will close it.

Thanks,
Sam

**Comment by samiit** [comment] 2016-06-24 04:20
I tried it at home (with no proxy, firewall, etc.), and got the following error:

ERROR: LoadError: getaddrinfo callback: no address (EAI_NODATA)
 in getaddrinfo at ./socket.jl:599
 in open_stream at /home/brothers/.julia/v0.4/Requests/src/streaming.jl:184
 in do_stream_request at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:286
 in post at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:407
 in post at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:406
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378

**Comment by samiit** [comment] 2016-06-25 04:17
I tried it at home (with no proxy, firewall, etc.), and got the following
error:

```
ERROR: getaddrinfo callback: no address (EAI_NODATA)
 in getaddrinfo at ./socket.jl:599
 in open_stream at /home/sam/.julia/v0.4/Requests/src/streaming.jl:184
 in do_stream_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:286
 in post at /home/sam/.julia/v0.4/Requests/src/Requests.jl:407
 in post at /home/sam/.julia/v0.4/Requests/src/Requests.jl:406
 in _send at /home/sam/.julia/v0.4/NEOS/src/NEOSServer.jl:42
 in _method at /home/sam/.julia/v0.4/NEOS/src/NEOSServer.jl:36
 in welcome at /home/sam/.julia/v0.4/NEOS/src/NEOSServer.jl:81

```

The command I executed were:

```
Pkg.checkout("NEOS")
using NEOS
s = NEOSServer()
println(welcome(s))

```

**Comment by odow** [comment] 2016-06-26 21:58
What does

```
using NEOS, Requests
s=NEOSServer()
@show s.host
uri = URI(s.host)
@show Base.getaddrinfo("neos-server.org")
@show Base.getaddrinfo(uri.host)
```

show?

**Comment by samiit** [comment] 2016-06-30 19:19
Sorry for being late with the answer. The output is:

s.host = "http://neos-server.org:3332"
Base.getaddrinfo("neos-server.org") = ip"144.92.142.147"
Base.getaddrinfo(uri.host) = ip"144.92.142.147"

**Comment by odow** [comment] 2016-07-01 01:50
Hi Samiit, 

No worries. I'm not really sure what the problem is. 

Have you tried the `welcome(s)` again?

Closing Julia and restarting?

```
using Requests
res = post("http://neos-server.org:3332";
    headers=Dict(
        "user-agent"=>"Julia_NEOS_jl",
        "host"=>"http://neos-server.org:3332",
        "content-type"=>"text/xml",
        "content-length"=>"0"
    ),
    data="")
@show res
```

**Comment by samiit** [comment] 2016-07-13 17:06
This is the output:

```
ERROR: getaddrinfo callback: no address (EAI_NODATA)
 in getaddrinfo at ./socket.jl:599
 in open_stream at /home/brothers/.julia/v0.4/Requests/src/streaming.jl:184
 in do_stream_request at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:286
 in post at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:407
 in post at /home/brothers/.julia/v0.4/Requests/src/Requests.jl:406

```

**Comment by odow** [comment] 2016-07-26 21:49
What happens when you try to ping the NEOS server?

```
julia>
shell> ping www.neos-server.org
```

Does `Requests` work for other websites?

```
using Requests
@show get("http://www.google.com")
```

**Comment by samiit** [comment] 2016-07-27 10:54
ping works

```
64 bytes from neos-1.neos-server.org (144.92.142.147): icmp_seq=2 ttl=47 time=273 ms
...
```

but, the get() function gives an error:

```
ERROR: getaddrinfo callback: unknown node or service (EAI_NONAME)
 in getaddrinfo at ./socket.jl:599
 in open_stream at /home/sam/.julia/v0.4/Requests/src/streaming.jl:184
 in do_stream_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:286
 in get at /home/sam/.julia/v0.4/Requests/src/Requests.jl:407
 in get at /home/sam/.julia/v0.4/Requests/src/Requests.jl:406
```

**Comment by samiit** [comment] 2016-08-12 06:56
Hi
I just migrated to Ubuntu 16.04 and installing Julia 0.45 shows proper output 

```
julia> @showget("http://www.neos-server.org")
get("http://www.neos-server.org") = Response(200 OK, 12 headers, 6465 bytes in body)
Response(200 OK, 12 headers, 6465 bytes in body)
```

I did this at my office where we work behind a proxy, and unfortunately, I still have the XML-RPC issue.

I'll check from home, whether the XML-RPC issue gets resolved over no-proxy and the new OS.

**Comment by odow** [comment] 2017-11-28 19:45
Closing for now as we at least [report the response status](https://github.com/odow/NEOS.jl/pull/16/files#diff-14b1233604f4286cc1b3955eba3db188R61) and it doesn't appear to be a NEOS.jl issue.

Please open a new issue if it remains a problem.

**Closed as completed by odow** 2017-11-28 19:45 UTC
